### ISSUE TITLE
[4.0.0-beta.7] Reloading in deep component leads to reloading the whole state (root component)

### ISSUE THREAD

**Issue by mqklin** [gaearon/react-hot-loader#749]
I have pretty big project with a lot of decorators. In v3 reloading in a deep and independent component leaded to reload only that component. Now if I reload `<Footer/>`, the whole `<App/>` will be reloaded as well.
My rough code structure:

```
import {hot} from 'react-hot-loader';
import React from 'react';
import {render} from 'react-dom';
import {Provider, connect} from 'react-redux';
import {BrowserRouter, withRouter} from 'react-router-dom';
import App from './App';
import store from './App/store';
const HotApp = hot(module)(App);

const HotConnectedApp = () => (
  <Provider store={store}>
    <BrowserRouter>
      <HotApp/>
    </BrowserRouter>
  </Provider>
);

render(
  <HotConnectedApp/>,
  document.getElementById('root'),
);

@withRouter
@connect(...)
class App extends Component {
  state = {
    initialFetchWasMade: false,
  };

  componentWillMount() {
    this.makeInitialFetchAndOnlyThenShowContent();
  }
  
  makeInitialFetchAndOnlyThenShowContent = () => {
    setTimeout(
      () => this.setState(() => ({initialFetchWasMade: true})),
      3000,
    );
  };
  
  render() {
    const {initialFetchWasMade} = this.state;
    if (initialFetchWasMade) return <Spinner/>;
    return (
      <div>
        <Header/>
        <Footer/>
      </div>
    );
  }
}
```

Now, if I make a change in `<Footer/>`, the whole `<App/>` reloads and `makeInitialFetchAndOnlyThenShowContent` is called every time (and it takes pretty long time sometimes). 
In v3 only `<Footer/>` was reloaded.

Is it a known bug? Should I create a repro?

**Comment by neoziro** [comment]
Yes it is a known bug in [4.0.0-beta.7] but it has no issue yet, you are so first one. Thanks.

**Comment by neoziro** [comment]
If you have a repro, it is welcome @theKashey will need it.

**Comment by neoziro** [comment]
Fixed in [4.0.0-beta.8]

**Comment by mqklin** [comment]
Still have this problem (beta.11)
Will be able to reproduce next week

**Comment by neoziro** [comment]
@mqklin yes, I will reopen it when we will have a repro

**Comment by mqklin** [comment]
Here is it: https://github.com/mqklin/rhl3-decorators-bug
```
import React, {Component} from 'react';

export default class App extends Component {
  state = {
    showInitialFetchSpinner: true,
  };

  componentDidMount() {
    setTimeout(
      () => this.setState(() => ({showInitialFetchSpinner: false})),
    1500,
    );
  };

  render() {
    const {showInitialFetchSpinner} = this.state;
    return (
      <div>
        {showInitialFetchSpinner && <div>Spinner...</div>}
        <Footer/>
      </div>
    );
  }
}

class Footer extends Component {
  render() {
    return <div>Footer (edit me)</div>;
  }
}
```
I expect that `<Footer/>` editing doesn't cause `<App/>` reloading and `componentDidMount` calling.

**Comment by theKashey** [comment]
You have to mark App as hot in App.js, not in index. 
(Anyway should work, let me check)

**Comment by theKashey** [comment]
Ok. This is a bug and a feature.
Why this a feature?
- it was designed to work like this. `hot` autoaccepts the changes, and trigger refresh after zero-timeout. On component refresh it perform all the work.
- in this case, just after the changes you will call `render`, and it will call `render` method of RHL, skipping the update step.
 - as result - everything got lost.

We expect, that you will mark as hot-exported __exports__ from some file, not imports.


Why this is a bug:
- we could call `update` method in AppContainer render. Easy, and will stop issues like this.

**Comment by mqklin** [comment]
@theKashey thank you! I moved `hot` to `App.js` and it works now.
If it's not a bug, it can be closed.

**Comment by theKashey** [comment]
This is a good example is the misconfiguration, we should be ready to handle.
So this is a bug.

**Comment by theKashey** [comment]
As long internal `generation` is just an `registration` counter, and does not reflect the number of hot-reloads, and could change in runtime (hello async components) - there is no way to autodetect this behavior. In most situations it will create a new AppContainer, without any react-tree it could reconcile with, causing or full Application remount in this case, and application __duplication__ in our styled-components example.

The only thing I could do - report that the component been unmounted was not on the last generation, ie was not upgraded, but they were, as long React first render a new tree, and next destroy the old one.

The same problem in #756 - we could not rely on `generation`, as long we also should use `reload`-counter, and different branches of code, behind different `hot` decorators, could have the different values.


So - there is no way to fix this issue. Yet.

**Comment by neoziro** [comment]
OK. Can we use something on `module` default export (or another export) matches with the component marked as hot?

**Comment by theKashey** [comment]
Sure we could add some magic member into `HotExported`, but who and when will match the signature?
The second problem - `module.exports` in case of webpack are wrapped by getter/setter and you could not iterate through them.

**Comment by neoziro** [comment]
OK, so no fix for now. I close this issue because the original bug is fixed. The discussion was about warn user about a misconfiguration but it is not possible for now.
